In [ ]:
# from google.colab import drive
# drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
recipe_name = "Recipe A: Pinwheels" #@param ["Recipe A: Pinwheels", "Recipe B: Pour-over Coffee"]
recipe_name_to_index = {"Recipe A: Pinwheels": "A", "Recipe B: Pour-over Coffee": "B", "Recipe C: Mug Cake":"C"}

In [ ]:
# path = "/content/drive/MyDrive/demo1/" #@param
path = "data/" #@param

In [ ]:
import numpy as np

def load_datasets_and_graphs(f_recipe,f_edges):
    """
    Args: 
        f_recipe: File path for outputs of feature extractor
        f_edges: File path for edges file for recipe
 
    Returns:
        dataset:size number of segments in video * number of sub-steps - each row contains the softmax over all the sub-steps in the given recipe
        edges: This array provides the dependency graph for the given recipe
    """
    dataset=np.load(f_recipe).astype(np.float64)
    # dataset=np.loadtxt(f_recipe,delimiter=",", dtype=np.float64)
    edges=np.load(f_edges).astype(np.uint32)
    return dataset,edges

def load_critical_mask_and_step_array(f_mask,f_array,num_sub_steps):
    """
    Args:
        f_mask: File path for critical steps mask for given recipe
        f_array: File path for end sub-step of each step

    Returns:
        mask: size - num_sub_steps*2 - Mask array for critical sub-steps (true if sub-step at index is critical)
        myarray: size - num_steps*2 - Contains the start and end sub-step index for each step
    """
    # sub_step_hp_path = os.path.join(f_mask)
    np_hp = np.loadtxt(f_mask, delimiter=",", dtype=np.uint32) - 1
    high_priority_masked_array = np.zeros(num_sub_steps, dtype=np.uint32)
    high_priority_masked_array[np_hp] = 1
    myarray=np.load(f_array).astype(np.uint32)
    return high_priority_masked_array,myarray

In [ ]:
dataset, edges = load_datasets_and_graphs(f"{path}sub_step_softmax/Recipe{recipe_name_to_index[recipe_name]}sub_step_outputs_sliding_window.npy",
                                          f"{path}edges/recipe{recipe_name_to_index[recipe_name]}_Edges.npy")
num_sub_steps=np.amax(edges) + 1
critical_mask, step_array=load_critical_mask_and_step_array(f'{path}high_priority/recipe{recipe_name_to_index[recipe_name]}', f'{path}sub_steps_in_steps/Recipe{recipe_name_to_index[recipe_name]}_sub_steps_in_step.npy', num_sub_steps)

In [ ]:
from particlefiltering import PF
print(critical_mask)
print(critical_mask.shape)
print(edges)
print(num_sub_steps)
print(dataset.shape)

'''
pf=PF(edges_pinwheels,critical_mask_pinwheels,step_array_pinwheels,num_sub_steps_pinwheels,100000)
for i in range(dataset_pinwheels.shape[0]):
  print(np.array(pf.update(dataset_pinwheels[i])))
'''
pf=PF(edges,critical_mask,step_array,num_sub_steps,1000)

# pf=PF(edges_coffee,critical_mask_coffee,step_array_coffee,num_sub_steps_coffee,1000)
for i in range(dataset.shape[0]):
  print(np.array(pf.update(dataset[i])))

[0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 1 1 1 1 0 0 0 0]
(27,)
[[ 0  1]
 [ 2  4]
 [ 3  4]
 [ 4  5]
 [ 6  7]
 [ 5  7]
 [ 7  8]
 [ 9 10]
 [10 11]
 [12 13]
 [11 13]
 [11 14]
 [15 16]
 [14 16]
 [16 17]
 [13 17]
 [18 19]
 [17 19]
 [19 20]
 [20 21]
 [21 22]
 [22 23]
 [23 24]
 [24 26]
 [25 26]]
27
(182, 27)
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 0 0 0 0 0 0 0 0 